services:
  - postgresql
language: python
python:
  - "3.6"
 command to install dependencies
branches:
  except:
    - testing

install:
  - pip install -r requirements.txt
  - psql -c 'create database rafs;' -U postgres
  - python manage.py migrate
script:
  - python manage.py test
