# Generated by Django 2.0 on 2018-02-19 16:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('product_picture', models.ImageField(blank=True, null=True, upload_to='image/product')),
                ('slug', models.SlugField()),
                ('category', models.ManyToManyField(to='category.Category')),
            ],
        ),
    ]
