# Generated by Django 2.0 on 2018-02-26 12:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name of category', max_length=20)),
                ('slug', models.SlugField()),
                ('summary', models.CharField(blank=True, help_text='Write Summary', max_length=200, null=True)),
                ('description', models.CharField(blank=True, help_text='Write Description', max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/category/')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
    ]
