# Generated by Django 2.0 on 2018-02-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_auto_20180226_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
    ]
