# Generated by Django 2.0 on 2018-02-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0003_auto_20180226_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='recommended',
            field=models.NullBooleanField(),
        ),
    ]
