# Generated by Django 2.0 on 2018-02-27 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('question_app', '0003_auto_20180227_1249'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relationship_app', '0004_relationship_recommended'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipWithQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, editable=False, null=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_app.Question')),
            ],
        ),
    ]
