# Generated by Django 2.0 on 2018-02-18 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20180218_1515'),
        ('category', '0003_auto_20180215_1536'),
    ]

    operations = [
    ]
