# Generated by Django 2.0 on 2018-02-18 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tag', '0001_initial'),
        ('product', '0002_auto_20180218_1515'),
        ('category', '0004_auto_20180218_1515'),
        ('question', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='asked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(to='category.Category'),
        ),
        migrations.AddField(
            model_name='question',
            name='downvoted_by',
            field=models.ManyToManyField(related_name='downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(to='tag.Tag'),
        ),
        migrations.AddField(
            model_name='question',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
