# Generated by Django 2.0 on 2018-02-23 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20180219_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ManyToManyField(blank=True, to='category.Category'),
        ),
        migrations.AlterField(
            model_name='question',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(blank=True, to='product.Product'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(blank=True, to='tag.Tag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
