# Generated by Django 2.0 on 2018-02-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='slug',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='selected_category',
            field=models.ManyToManyField(blank=True, to='category.Category'),
        ),
    ]
